
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  About: typeof import("../../app/components/About.vue")['default']
  Acc: typeof import("../../app/components/Acc.vue")['default']
  AppFooter: typeof import("../../app/components/AppFooter.vue")['default']
  AppHeader: typeof import("../../app/components/AppHeader.vue")['default']
  Card: typeof import("../../app/components/Card.vue")['default']
  Cards: typeof import("../../app/components/Cards.vue")['default']
  Cart: typeof import("../../app/components/Cart.vue")['default']
  ColorThief: typeof import("../../app/components/ColorThief.vue")['default']
  Entry: typeof import("../../app/components/Entry.vue")['default']
  ImageGenerator: typeof import("../../app/components/ImageGenerator.vue")['default']
  New: typeof import("../../app/components/New.vue")['default']
  New2: typeof import("../../app/components/New2.vue")['default']
  Slider: typeof import("../../app/components/Slider.vue")['default']
  Slider2: typeof import("../../app/components/Slider2.vue")['default']
  Stripe: typeof import("../../app/components/Stripe.vue")['default']
  Ac: typeof import("../../app/components/ac.vue")['default']
  Ac1: typeof import("../../app/components/ac1.vue")['default']
  Ac2: typeof import("../../app/components/ac2.vue")['default']
  Btn1: typeof import("../../app/components/btn1.vue")['default']
  Btn99: typeof import("../../app/components/btn99.vue")['default']
  Btns: typeof import("../../app/components/btns.vue")['default']
  Fm1: typeof import("../../app/components/fm1.vue")['default']
  Fm2: typeof import("../../app/components/fm2.vue")['default']
  H: typeof import("../../app/components/h.vue")['default']
  Hd: typeof import("../../app/components/hd.vue")['default']
  Inp1: typeof import("../../app/components/inp1.vue")['default']
  Inp2: typeof import("../../app/components/inp2.vue")['default']
  Inp3: typeof import("../../app/components/inp3.vue")['default']
  Inp4: typeof import("../../app/components/inp4.vue")['default']
  Inp5: typeof import("../../app/components/inp5.vue")['default']
  Kbd: typeof import("../../app/components/kbd.vue")['default']
  Lbl: typeof import("../../app/components/lbl.vue")['default']
  Li1: typeof import("../../app/components/li1.vue")['default']
  Li2: typeof import("../../app/components/li2.vue")['default']
  Mega: typeof import("../../app/components/mega.vue")['default']
  Mlw1: typeof import("../../app/components/mlw1.vue")['default']
  Mlw2: typeof import("../../app/components/mlw2.vue")['default']
  Nav: typeof import("../../app/components/nav.vue")['default']
  Nf: typeof import("../../app/components/nf.vue")['default']
  Not: typeof import("../../app/components/not.vue")['default']
  Not1: typeof import("../../app/components/not1.vue")['default']
  P1: typeof import("../../app/components/p1.vue")['default']
  Pul: typeof import("../../app/components/pul.vue")['default']
  Se: typeof import("../../app/components/se.vue")['default']
  Spn: typeof import("../../app/components/spn.vue")['default']
  Tabs: typeof import("../../app/components/tabs.vue")['default']
  Tbl: typeof import("../../app/components/tbl.vue")['default']
  UAside: typeof import("../../node_modules/@nuxt/ui-pro/components/aside/Aside.vue")['default']
  UAsideLinks: typeof import("../../node_modules/@nuxt/ui-pro/components/aside/AsideLinks.vue")['default']
  UAuthForm: typeof import("../../node_modules/@nuxt/ui-pro/components/auth/AuthForm.vue")['default']
  UBlogList: typeof import("../../node_modules/@nuxt/ui-pro/components/blog/BlogList.vue")['default']
  UBlogPost: typeof import("../../node_modules/@nuxt/ui-pro/components/blog/BlogPost.vue")['default']
  UColorModeAvatar: typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeAvatar.vue")['default']
  UColorModeButton: typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeButton.vue")['default']
  UColorModeImage: typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeImage.vue")['default']
  UColorModeSelect: typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeSelect.vue")['default']
  UColorModeToggle: typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeToggle.vue")['default']
  UDashboardCard: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardCard.vue")['default']
  UDashboardLayout: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardLayout.vue")['default']
  UDashboardModal: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardModal.vue")['default']
  UDashboardNavbar: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbar.vue")['default']
  UDashboardNavbarToggle: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbarToggle.vue")['default']
  UDashboardPage: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPage.vue")['default']
  UDashboardPanel: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanel.vue")['default']
  UDashboardPanelContent: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelContent.vue")['default']
  UDashboardPanelHandle: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelHandle.vue")['default']
  UDashboardSearch: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearch.vue")['default']
  UDashboardSearchButton: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearchButton.vue")['default']
  UDashboardSection: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSection.vue")['default']
  UDashboardSidebar: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebar.vue")['default']
  UDashboardSidebarLinks: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebarLinks.vue")['default']
  UDashboardSlideover: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSlideover.vue")['default']
  UDashboardToolbar: typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardToolbar.vue")['default']
  UFooter: typeof import("../../node_modules/@nuxt/ui-pro/components/footer/Footer.vue")['default']
  UFooterColumns: typeof import("../../node_modules/@nuxt/ui-pro/components/footer/FooterColumns.vue")['default']
  UFooterLinks: typeof import("../../node_modules/@nuxt/ui-pro/components/footer/FooterLinks.vue")['default']
  UHeader: typeof import("../../node_modules/@nuxt/ui-pro/components/header/Header.vue")['default']
  UHeaderLinks: typeof import("../../node_modules/@nuxt/ui-pro/components/header/HeaderLinks.vue")['default']
  UHeaderPopoverLinks: typeof import("../../node_modules/@nuxt/ui-pro/components/header/HeaderPopoverLinks.vue")['default']
  ULandingCTA: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingCTA.vue")['default']
  ULandingCard: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingCard.vue")['default']
  ULandingFAQ: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingFAQ.vue")['default']
  ULandingGrid: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingGrid.vue")['default']
  ULandingHero: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingHero.vue")['default']
  ULandingLogos: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingLogos.vue")['default']
  ULandingSection: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingSection.vue")['default']
  ULandingTestimonial: typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingTestimonial.vue")['default']
  UMain: typeof import("../../node_modules/@nuxt/ui-pro/components/main/Main.vue")['default']
  UNavigationAccordion: typeof import("../../node_modules/@nuxt/ui-pro/components/navigation/NavigationAccordion.vue")['default']
  UNavigationLinks: typeof import("../../node_modules/@nuxt/ui-pro/components/navigation/NavigationLinks.vue")['default']
  UNavigationTree: typeof import("../../node_modules/@nuxt/ui-pro/components/navigation/NavigationTree.vue")['default']
  UPage: typeof import("../../node_modules/@nuxt/ui-pro/components/page/Page.vue")['default']
  UPageBody: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageBody.vue")['default']
  UPageCard: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageCard.vue")['default']
  UPageColumns: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageColumns.vue")['default']
  UPageError: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageError.vue")['default']
  UPageGrid: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageGrid.vue")['default']
  UPageHeader: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageHeader.vue")['default']
  UPageHero: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageHero.vue")['default']
  UPageLinks: typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageLinks.vue")['default']
  UPricingCard: typeof import("../../node_modules/@nuxt/ui-pro/components/pricing/PricingCard.vue")['default']
  UPricingGrid: typeof import("../../node_modules/@nuxt/ui-pro/components/pricing/PricingGrid.vue")['default']
  UPricingToggle: typeof import("../../node_modules/@nuxt/ui-pro/components/pricing/PricingToggle.vue")['default']
  Callout: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Callout.vue")['default']
  CardGroup: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/CardGroup.vue")['default']
  CodeGroup: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/CodeGroup.vue")['default']
  Collapsible: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Collapsible.vue")['default']
  Field: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Field.vue")['default']
  FieldGroup: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/FieldGroup.vue")['default']
  Shortcut: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Shortcut.vue")['default']
  ProseCode: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseCode.vue")['default']
  ProseCodeButton: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseCodeButton.vue")['default']
  ProseCodeIcon: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseCodeIcon.vue")['default']
  ProseH1: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH1.vue")['default']
  ProseH2: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH2.vue")['default']
  ProseH3: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH3.vue")['default']
  ProseH4: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH4.vue")['default']
  UContentSearch: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSearch.vue")['default']
  UContentSearchButton: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSearchButton.vue")['default']
  UContentSurround: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSurround.vue")['default']
  UContentSurroundLink: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSurroundLink.vue")['default']
  UContentToc: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentToc.vue")['default']
  UContentTocLinks: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentTocLinks.vue")['default']
  UDocsSearch: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSearch")['default']
  UDocsSearchButton: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSearchButton")['default']
  UDocsSurround: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSurround")['default']
  UDocsSurroundLink: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSurroundLink")['default']
  UDocsToc: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsToc")['default']
  UDocsTocLinks: typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsTocLinks")['default']
  ContentDoc: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
  ContentList: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
  ContentNavigation: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
  ContentQuery: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
  ContentRenderer: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
  ContentRendererMarkdown: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
  ContentSlot: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
  DocumentDrivenEmpty: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
  DocumentDrivenNotFound: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
  Markdown: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
  ProseCodeInline: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
  ProsePre: typeof import("../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
  ProseA: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
  ProseBlockquote: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
  ProseEm: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
  ProseH5: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
  ProseH6: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
  ProseHr: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
  ProseImg: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
  ProseLi: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
  ProseOl: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
  ProseP: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
  ProseScript: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
  ProseStrong: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
  ProseTable: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
  ProseTbody: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
  ProseTd: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
  ProseTh: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
  ProseThead: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
  ProseTr: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
  ProseUl: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
  UAccordion: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
  UAlert: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
  UAvatar: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
  UAvatarGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
  UBadge: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
  UButton: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
  UButtonGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
  UCarousel: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
  UChip: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
  UDropdown: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
  UIcon: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
  UKbd: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
  ULink: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
  UMeter: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
  UMeterGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
  UProgress: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
  UCheckbox: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
  UForm: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
  UFormGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
  UInput: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
  UInputMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
  URadio: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
  URadioGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
  URange: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
  USelect: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
  USelectMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
  UTextarea: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
  UToggle: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
  UTable: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
  UCard: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
  UContainer: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
  UDivider: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
  USkeleton: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
  UBreadcrumb: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
  UCommandPalette: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
  UCommandPaletteGroup: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
  UHorizontalNavigation: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
  UPagination: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
  UTabs: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
  UVerticalNavigation: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
  UContextMenu: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
  UModal: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
  UModals: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
  UNotification: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
  UNotifications: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
  UPopover: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
  USlideover: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
  USlideovers: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
  UTooltip: typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  NuxtPicture: typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  MDC: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
  MDCRenderer: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
  MDCSlot: typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
  Icon: typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  ColorScheme: typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAbout: LazyComponent<typeof import("../../app/components/About.vue")['default']>
  LazyAcc: LazyComponent<typeof import("../../app/components/Acc.vue")['default']>
  LazyAppFooter: LazyComponent<typeof import("../../app/components/AppFooter.vue")['default']>
  LazyAppHeader: LazyComponent<typeof import("../../app/components/AppHeader.vue")['default']>
  LazyCard: LazyComponent<typeof import("../../app/components/Card.vue")['default']>
  LazyCards: LazyComponent<typeof import("../../app/components/Cards.vue")['default']>
  LazyCart: LazyComponent<typeof import("../../app/components/Cart.vue")['default']>
  LazyColorThief: LazyComponent<typeof import("../../app/components/ColorThief.vue")['default']>
  LazyEntry: LazyComponent<typeof import("../../app/components/Entry.vue")['default']>
  LazyImageGenerator: LazyComponent<typeof import("../../app/components/ImageGenerator.vue")['default']>
  LazyNew: LazyComponent<typeof import("../../app/components/New.vue")['default']>
  LazyNew2: LazyComponent<typeof import("../../app/components/New2.vue")['default']>
  LazySlider: LazyComponent<typeof import("../../app/components/Slider.vue")['default']>
  LazySlider2: LazyComponent<typeof import("../../app/components/Slider2.vue")['default']>
  LazyStripe: LazyComponent<typeof import("../../app/components/Stripe.vue")['default']>
  LazyAc: LazyComponent<typeof import("../../app/components/ac.vue")['default']>
  LazyAc1: LazyComponent<typeof import("../../app/components/ac1.vue")['default']>
  LazyAc2: LazyComponent<typeof import("../../app/components/ac2.vue")['default']>
  LazyBtn1: LazyComponent<typeof import("../../app/components/btn1.vue")['default']>
  LazyBtn99: LazyComponent<typeof import("../../app/components/btn99.vue")['default']>
  LazyBtns: LazyComponent<typeof import("../../app/components/btns.vue")['default']>
  LazyFm1: LazyComponent<typeof import("../../app/components/fm1.vue")['default']>
  LazyFm2: LazyComponent<typeof import("../../app/components/fm2.vue")['default']>
  LazyH: LazyComponent<typeof import("../../app/components/h.vue")['default']>
  LazyHd: LazyComponent<typeof import("../../app/components/hd.vue")['default']>
  LazyInp1: LazyComponent<typeof import("../../app/components/inp1.vue")['default']>
  LazyInp2: LazyComponent<typeof import("../../app/components/inp2.vue")['default']>
  LazyInp3: LazyComponent<typeof import("../../app/components/inp3.vue")['default']>
  LazyInp4: LazyComponent<typeof import("../../app/components/inp4.vue")['default']>
  LazyInp5: LazyComponent<typeof import("../../app/components/inp5.vue")['default']>
  LazyKbd: LazyComponent<typeof import("../../app/components/kbd.vue")['default']>
  LazyLbl: LazyComponent<typeof import("../../app/components/lbl.vue")['default']>
  LazyLi1: LazyComponent<typeof import("../../app/components/li1.vue")['default']>
  LazyLi2: LazyComponent<typeof import("../../app/components/li2.vue")['default']>
  LazyMega: LazyComponent<typeof import("../../app/components/mega.vue")['default']>
  LazyMlw1: LazyComponent<typeof import("../../app/components/mlw1.vue")['default']>
  LazyMlw2: LazyComponent<typeof import("../../app/components/mlw2.vue")['default']>
  LazyNav: LazyComponent<typeof import("../../app/components/nav.vue")['default']>
  LazyNf: LazyComponent<typeof import("../../app/components/nf.vue")['default']>
  LazyNot: LazyComponent<typeof import("../../app/components/not.vue")['default']>
  LazyNot1: LazyComponent<typeof import("../../app/components/not1.vue")['default']>
  LazyP1: LazyComponent<typeof import("../../app/components/p1.vue")['default']>
  LazyPul: LazyComponent<typeof import("../../app/components/pul.vue")['default']>
  LazySe: LazyComponent<typeof import("../../app/components/se.vue")['default']>
  LazySpn: LazyComponent<typeof import("../../app/components/spn.vue")['default']>
  LazyTabs: LazyComponent<typeof import("../../app/components/tabs.vue")['default']>
  LazyTbl: LazyComponent<typeof import("../../app/components/tbl.vue")['default']>
  LazyUAside: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/aside/Aside.vue")['default']>
  LazyUAsideLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/aside/AsideLinks.vue")['default']>
  LazyUAuthForm: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/auth/AuthForm.vue")['default']>
  LazyUBlogList: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/blog/BlogList.vue")['default']>
  LazyUBlogPost: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/blog/BlogPost.vue")['default']>
  LazyUColorModeAvatar: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeAvatar.vue")['default']>
  LazyUColorModeButton: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeButton.vue")['default']>
  LazyUColorModeImage: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeImage.vue")['default']>
  LazyUColorModeSelect: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeSelect.vue")['default']>
  LazyUColorModeToggle: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/color-mode/ColorModeToggle.vue")['default']>
  LazyUDashboardCard: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardCard.vue")['default']>
  LazyUDashboardLayout: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardLayout.vue")['default']>
  LazyUDashboardModal: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardModal.vue")['default']>
  LazyUDashboardNavbar: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbar.vue")['default']>
  LazyUDashboardNavbarToggle: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardNavbarToggle.vue")['default']>
  LazyUDashboardPage: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPage.vue")['default']>
  LazyUDashboardPanel: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanel.vue")['default']>
  LazyUDashboardPanelContent: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelContent.vue")['default']>
  LazyUDashboardPanelHandle: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardPanelHandle.vue")['default']>
  LazyUDashboardSearch: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearch.vue")['default']>
  LazyUDashboardSearchButton: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSearchButton.vue")['default']>
  LazyUDashboardSection: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSection.vue")['default']>
  LazyUDashboardSidebar: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebar.vue")['default']>
  LazyUDashboardSidebarLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSidebarLinks.vue")['default']>
  LazyUDashboardSlideover: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardSlideover.vue")['default']>
  LazyUDashboardToolbar: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/dashboard/DashboardToolbar.vue")['default']>
  LazyUFooter: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/footer/Footer.vue")['default']>
  LazyUFooterColumns: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/footer/FooterColumns.vue")['default']>
  LazyUFooterLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/footer/FooterLinks.vue")['default']>
  LazyUHeader: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/header/Header.vue")['default']>
  LazyUHeaderLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/header/HeaderLinks.vue")['default']>
  LazyUHeaderPopoverLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/header/HeaderPopoverLinks.vue")['default']>
  LazyULandingCTA: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingCTA.vue")['default']>
  LazyULandingCard: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingCard.vue")['default']>
  LazyULandingFAQ: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingFAQ.vue")['default']>
  LazyULandingGrid: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingGrid.vue")['default']>
  LazyULandingHero: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingHero.vue")['default']>
  LazyULandingLogos: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingLogos.vue")['default']>
  LazyULandingSection: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingSection.vue")['default']>
  LazyULandingTestimonial: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/landing/LandingTestimonial.vue")['default']>
  LazyUMain: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/main/Main.vue")['default']>
  LazyUNavigationAccordion: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/navigation/NavigationAccordion.vue")['default']>
  LazyUNavigationLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/navigation/NavigationLinks.vue")['default']>
  LazyUNavigationTree: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/navigation/NavigationTree.vue")['default']>
  LazyUPage: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/Page.vue")['default']>
  LazyUPageBody: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageBody.vue")['default']>
  LazyUPageCard: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageCard.vue")['default']>
  LazyUPageColumns: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageColumns.vue")['default']>
  LazyUPageError: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageError.vue")['default']>
  LazyUPageGrid: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageGrid.vue")['default']>
  LazyUPageHeader: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageHeader.vue")['default']>
  LazyUPageHero: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageHero.vue")['default']>
  LazyUPageLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/page/PageLinks.vue")['default']>
  LazyUPricingCard: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/pricing/PricingCard.vue")['default']>
  LazyUPricingGrid: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/pricing/PricingGrid.vue")['default']>
  LazyUPricingToggle: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/components/pricing/PricingToggle.vue")['default']>
  LazyCallout: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Callout.vue")['default']>
  LazyCardGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/CardGroup.vue")['default']>
  LazyCodeGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/CodeGroup.vue")['default']>
  LazyCollapsible: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Collapsible.vue")['default']>
  LazyField: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Field.vue")['default']>
  LazyFieldGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/FieldGroup.vue")['default']>
  LazyShortcut: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/Shortcut.vue")['default']>
  LazyProseCode: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseCode.vue")['default']>
  LazyProseCodeButton: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseCodeButton.vue")['default']>
  LazyProseCodeIcon: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseCodeIcon.vue")['default']>
  LazyProseH1: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH1.vue")['default']>
  LazyProseH2: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH2.vue")['default']>
  LazyProseH3: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH3.vue")['default']>
  LazyProseH4: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/global/prose/ProseH4.vue")['default']>
  LazyUContentSearch: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSearch.vue")['default']>
  LazyUContentSearchButton: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSearchButton.vue")['default']>
  LazyUContentSurround: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSurround.vue")['default']>
  LazyUContentSurroundLink: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentSurroundLink.vue")['default']>
  LazyUContentToc: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentToc.vue")['default']>
  LazyUContentTocLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/content/ContentTocLinks.vue")['default']>
  LazyUDocsSearch: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSearch")['default']>
  LazyUDocsSearchButton: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSearchButton")['default']>
  LazyUDocsSurround: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSurround")['default']>
  LazyUDocsSurroundLink: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsSurroundLink")['default']>
  LazyUDocsToc: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsToc")['default']>
  LazyUDocsTocLinks: LazyComponent<typeof import("../../node_modules/@nuxt/ui-pro/modules/pro/runtime/components/docs/DocsTocLinks")['default']>
  LazyContentDoc: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']>
  LazyContentList: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']>
  LazyContentNavigation: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']>
  LazyContentQuery: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']>
  LazyContentRenderer: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
  LazyContentRendererMarkdown: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']>
  LazyContentSlot: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']>
  LazyDocumentDrivenEmpty: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']>
  LazyDocumentDrivenNotFound: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']>
  LazyMarkdown: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']>
  LazyProseCodeInline: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']>
  LazyProsePre: LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']>
  LazyProseA: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
  LazyProseBlockquote: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
  LazyProseEm: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
  LazyProseH5: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
  LazyProseH6: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
  LazyProseHr: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
  LazyProseImg: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
  LazyProseLi: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
  LazyProseOl: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
  LazyProseP: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
  LazyProseScript: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
  LazyProseStrong: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
  LazyProseTable: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
  LazyProseTbody: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
  LazyProseTd: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
  LazyProseTh: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
  LazyProseThead: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
  LazyProseTr: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
  LazyProseUl: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
  LazyUAccordion: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']>
  LazyUAlert: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']>
  LazyUAvatar: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']>
  LazyUAvatarGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']>
  LazyUBadge: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']>
  LazyUButton: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']>
  LazyUButtonGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']>
  LazyUCarousel: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']>
  LazyUChip: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']>
  LazyUDropdown: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']>
  LazyUIcon: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']>
  LazyUKbd: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']>
  LazyULink: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']>
  LazyUMeter: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']>
  LazyUMeterGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']>
  LazyUProgress: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']>
  LazyUCheckbox: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']>
  LazyUForm: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']>
  LazyUFormGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']>
  LazyUInput: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']>
  LazyUInputMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']>
  LazyURadio: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']>
  LazyURadioGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']>
  LazyURange: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']>
  LazyUSelect: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']>
  LazyUSelectMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']>
  LazyUTextarea: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']>
  LazyUToggle: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']>
  LazyUTable: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']>
  LazyUCard: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']>
  LazyUContainer: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']>
  LazyUDivider: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']>
  LazyUSkeleton: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']>
  LazyUBreadcrumb: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']>
  LazyUCommandPalette: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']>
  LazyUCommandPaletteGroup: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']>
  LazyUHorizontalNavigation: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']>
  LazyUPagination: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']>
  LazyUTabs: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']>
  LazyUVerticalNavigation: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']>
  LazyUContextMenu: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']>
  LazyUModal: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']>
  LazyUModals: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']>
  LazyUNotification: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']>
  LazyUNotifications: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']>
  LazyUPopover: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']>
  LazyUSlideover: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']>
  LazyUSlideovers: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']>
  LazyUTooltip: LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  LazyMDC: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
  LazyMDCRenderer: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
  LazyMDCSlot: LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
  LazyIcon: LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  LazyColorScheme: LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
