<template>
  <nav class="relative">
    <ul>
      <li><a class="group relative flex items-center gap-1.5 focus:outline-none focus-visible:outline-none dark:focus-visible:outline-none focus-visible:before:ring-inset focus-visible:before:ring-1 focus-visible:before:ring-primary-500 dark:focus-visible:before:ring-primary-400 before:absolute before:inset-px before:rounded-md disabled:cursor-not-allowed disabled:opacity-75 px-2.5 py-1.5 w-full focus-visible:ring-inset focus-visible:ring-2 focus-visible:ring-primary-500 dark:focus-visible:ring-primary-400 rounded-md font-medium text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:before:bg-gray-50 dark:hover:before:bg-gray-800/50" href="#"><span class="relative inline-flex items-center justify-center flex-shrink-0 rounded-full h-5 w-5 text-[10px]"><img class="rounded-full h-5 w-5 text-[10px]" src="https://ipx.nuxt.com/s_16x16/gh_avatar/benjamincanac" srcset="https://ipx.nuxt.com/s_32x32/gh_avatar/benjamincanac 2x" loading="lazy"></span><span class="truncate relative"> benjamincanac</span></a></li>
      <li><a class="group relative flex items-center gap-1.5 focus:outline-none focus-visible:outline-none dark:focus-visible:outline-none focus-visible:before:ring-inset focus-visible:before:ring-1 focus-visible:before:ring-primary-500 dark:focus-visible:before:ring-primary-400 before:absolute before:inset-px before:rounded-md disabled:cursor-not-allowed disabled:opacity-75 px-2.5 py-1.5 w-full focus-visible:ring-inset focus-visible:ring-2 focus-visible:ring-primary-500 dark:focus-visible:ring-primary-400 rounded-md font-medium text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:before:bg-gray-50 dark:hover:before:bg-gray-800/50" href="#"><span class="relative inline-flex items-center justify-center flex-shrink-0 rounded-full h-5 w-5 text-[10px]"><img class="rounded-full h-5 w-5 text-[10px]" src="https://ipx.nuxt.com/s_16x16/gh_avatar/Atinux" srcset="https://ipx.nuxt.com/s_32x32/gh_avatar/Atinux 2x" loading="lazy"></span><span class="truncate relative"> Atinux</span></a></li>
      <li><a class="group relative flex items-center gap-1.5 focus:outline-none focus-visible:outline-none dark:focus-visible:outline-none focus-visible:before:ring-inset focus-visible:before:ring-1 focus-visible:before:ring-primary-500 dark:focus-visible:before:ring-primary-400 before:absolute before:inset-px before:rounded-md disabled:cursor-not-allowed disabled:opacity-75 px-2.5 py-1.5 w-full focus-visible:ring-inset focus-visible:ring-2 focus-visible:ring-primary-500 dark:focus-visible:ring-primary-400 rounded-md font-medium text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:before:bg-gray-50 dark:hover:before:bg-gray-800/50" href="#"><span class="relative inline-flex items-center justify-center flex-shrink-0 rounded-full h-5 w-5 text-[10px]"><img class="rounded-full h-5 w-5 text-[10px]" src="https://ipx.nuxt.com/s_16x16/gh_avatar/smarroufin" srcset="https://ipx.nuxt.com/s_32x32/gh_avatar/smarroufin 2x" loading="lazy"></span><span class="truncate relative">smarroufin</span></a></li>
    </ul>
  </nav>
</template>
